/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppRelatorioRouteImport } from './routes/app.relatorio'
import { Route as AppReceitasRouteImport } from './routes/app.receitas'
import { Route as AppPesoRouteImport } from './routes/app.peso'
import { Route as AppNutricaoHistoricoRouteImport } from './routes/app.nutricao-historico'
import { Route as AppNutricaoRouteImport } from './routes/app.nutricao'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppLembretesRouteImport } from './routes/app.lembretes'
import { Route as AppExerciciosRouteImport } from './routes/app.exercicios'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppTreinosIndexRouteImport } from './routes/app.treinos.index'
import { Route as AppTemplatesIndexRouteImport } from './routes/app.templates.index'
import { Route as AppReceitasIndexRouteImport } from './routes/app.receitas.index'
import { Route as AppTreinosIdRouteImport } from './routes/app.treinos.$id'
import { Route as AppTemplatesIdRouteImport } from './routes/app.templates.$id'
import { Route as AppReceitasIdRouteImport } from './routes/app.receitas.$id'
import { Route as AppExerciciosNameRouteImport } from './routes/app.exercicios.$name'
import { Route as AppTreinosIdFocoRouteImport } from './routes/app.treinos.$id.foco'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatorioRoute = AppRelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppPesoRoute = AppPesoRouteImport.update({
  id: '/peso',
  path: '/peso',
  getParentRoute: () => AppRoute,
} as any)
const AppNutricaoHistoricoRoute = AppNutricaoHistoricoRouteImport.update({
  id: '/nutricao-historico',
  path: '/nutricao-historico',
  getParentRoute: () => AppRoute,
} as any)
const AppNutricaoRoute = AppNutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppLembretesRoute = AppLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => AppRoute,
} as any)
const AppExerciciosRoute = AppExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosIndexRoute = AppTreinosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTreinosRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppReceitasIndexRoute = AppReceitasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReceitasRoute,
} as any)
const AppTreinosIdRoute = AppTreinosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTreinosRoute,
} as any)
const AppTemplatesIdRoute = AppTemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppReceitasIdRoute = AppReceitasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppReceitasRoute,
} as any)
const AppExerciciosNameRoute = AppExerciciosNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppExerciciosRoute,
} as any)
const AppTreinosIdFocoRoute = AppTreinosIdFocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => AppTreinosIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/chat': typeof AppChatRoute
  '/app/coach': typeof AppCoachRoute
  '/app/exercicios': typeof AppExerciciosRouteWithChildren
  '/app/lembretes': typeof AppLembretesRoute
  '/app/metas': typeof AppMetasRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/nutricao-historico': typeof AppNutricaoHistoricoRoute
  '/app/peso': typeof AppPesoRoute
  '/app/receitas': typeof AppReceitasRouteWithChildren
  '/app/relatorio': typeof AppRelatorioRoute
  '/app/templates': typeof AppTemplatesRouteWithChildren
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/exercicios/$name': typeof AppExerciciosNameRoute
  '/app/receitas/$id': typeof AppReceitasIdRoute
  '/app/templates/$id': typeof AppTemplatesIdRoute
  '/app/treinos/$id': typeof AppTreinosIdRouteWithChildren
  '/app/receitas/': typeof AppReceitasIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/treinos/': typeof AppTreinosIndexRoute
  '/app/treinos/$id/foco': typeof AppTreinosIdFocoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/chat': typeof AppChatRoute
  '/app/coach': typeof AppCoachRoute
  '/app/exercicios': typeof AppExerciciosRouteWithChildren
  '/app/lembretes': typeof AppLembretesRoute
  '/app/metas': typeof AppMetasRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/nutricao-historico': typeof AppNutricaoHistoricoRoute
  '/app/peso': typeof AppPesoRoute
  '/app/relatorio': typeof AppRelatorioRoute
  '/app': typeof AppIndexRoute
  '/app/exercicios/$name': typeof AppExerciciosNameRoute
  '/app/receitas/$id': typeof AppReceitasIdRoute
  '/app/templates/$id': typeof AppTemplatesIdRoute
  '/app/treinos/$id': typeof AppTreinosIdRouteWithChildren
  '/app/receitas': typeof AppReceitasIndexRoute
  '/app/templates': typeof AppTemplatesIndexRoute
  '/app/treinos': typeof AppTreinosIndexRoute
  '/app/treinos/$id/foco': typeof AppTreinosIdFocoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/chat': typeof AppChatRoute
  '/app/coach': typeof AppCoachRoute
  '/app/exercicios': typeof AppExerciciosRouteWithChildren
  '/app/lembretes': typeof AppLembretesRoute
  '/app/metas': typeof AppMetasRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/nutricao-historico': typeof AppNutricaoHistoricoRoute
  '/app/peso': typeof AppPesoRoute
  '/app/receitas': typeof AppReceitasRouteWithChildren
  '/app/relatorio': typeof AppRelatorioRoute
  '/app/templates': typeof AppTemplatesRouteWithChildren
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/exercicios/$name': typeof AppExerciciosNameRoute
  '/app/receitas/$id': typeof AppReceitasIdRoute
  '/app/templates/$id': typeof AppTemplatesIdRoute
  '/app/treinos/$id': typeof AppTreinosIdRouteWithChildren
  '/app/receitas/': typeof AppReceitasIndexRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/treinos/': typeof AppTreinosIndexRoute
  '/app/treinos/$id/foco': typeof AppTreinosIdFocoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/chat'
    | '/app/coach'
    | '/app/exercicios'
    | '/app/lembretes'
    | '/app/metas'
    | '/app/nutricao'
    | '/app/nutricao-historico'
    | '/app/peso'
    | '/app/receitas'
    | '/app/relatorio'
    | '/app/templates'
    | '/app/treinos'
    | '/app/'
    | '/app/exercicios/$name'
    | '/app/receitas/$id'
    | '/app/templates/$id'
    | '/app/treinos/$id'
    | '/app/receitas/'
    | '/app/templates/'
    | '/app/treinos/'
    | '/app/treinos/$id/foco'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/chat'
    | '/app/coach'
    | '/app/exercicios'
    | '/app/lembretes'
    | '/app/metas'
    | '/app/nutricao'
    | '/app/nutricao-historico'
    | '/app/peso'
    | '/app/relatorio'
    | '/app'
    | '/app/exercicios/$name'
    | '/app/receitas/$id'
    | '/app/templates/$id'
    | '/app/treinos/$id'
    | '/app/receitas'
    | '/app/templates'
    | '/app/treinos'
    | '/app/treinos/$id/foco'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/chat'
    | '/app/coach'
    | '/app/exercicios'
    | '/app/lembretes'
    | '/app/metas'
    | '/app/nutricao'
    | '/app/nutricao-historico'
    | '/app/peso'
    | '/app/receitas'
    | '/app/relatorio'
    | '/app/templates'
    | '/app/treinos'
    | '/app/'
    | '/app/exercicios/$name'
    | '/app/receitas/$id'
    | '/app/templates/$id'
    | '/app/treinos/$id'
    | '/app/receitas/'
    | '/app/templates/'
    | '/app/treinos/'
    | '/app/treinos/$id/foco'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorio': {
      id: '/app/relatorio'
      path: '/relatorio'
      fullPath: '/app/relatorio'
      preLoaderRoute: typeof AppRelatorioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/receitas': {
      id: '/app/receitas'
      path: '/receitas'
      fullPath: '/app/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peso': {
      id: '/app/peso'
      path: '/peso'
      fullPath: '/app/peso'
      preLoaderRoute: typeof AppPesoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutricao-historico': {
      id: '/app/nutricao-historico'
      path: '/nutricao-historico'
      fullPath: '/app/nutricao-historico'
      preLoaderRoute: typeof AppNutricaoHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutricao': {
      id: '/app/nutricao'
      path: '/nutricao'
      fullPath: '/app/nutricao'
      preLoaderRoute: typeof AppNutricaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lembretes': {
      id: '/app/lembretes'
      path: '/lembretes'
      fullPath: '/app/lembretes'
      preLoaderRoute: typeof AppLembretesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exercicios': {
      id: '/app/exercicios'
      path: '/exercicios'
      fullPath: '/app/exercicios'
      preLoaderRoute: typeof AppExerciciosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos/': {
      id: '/app/treinos/'
      path: '/'
      fullPath: '/app/treinos/'
      preLoaderRoute: typeof AppTreinosIndexRouteImport
      parentRoute: typeof AppTreinosRoute
    }
    '/app/templates/': {
      id: '/app/templates/'
      path: '/'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/app/receitas/': {
      id: '/app/receitas/'
      path: '/'
      fullPath: '/app/receitas/'
      preLoaderRoute: typeof AppReceitasIndexRouteImport
      parentRoute: typeof AppReceitasRoute
    }
    '/app/treinos/$id': {
      id: '/app/treinos/$id'
      path: '/$id'
      fullPath: '/app/treinos/$id'
      preLoaderRoute: typeof AppTreinosIdRouteImport
      parentRoute: typeof AppTreinosRoute
    }
    '/app/templates/$id': {
      id: '/app/templates/$id'
      path: '/$id'
      fullPath: '/app/templates/$id'
      preLoaderRoute: typeof AppTemplatesIdRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/app/receitas/$id': {
      id: '/app/receitas/$id'
      path: '/$id'
      fullPath: '/app/receitas/$id'
      preLoaderRoute: typeof AppReceitasIdRouteImport
      parentRoute: typeof AppReceitasRoute
    }
    '/app/exercicios/$name': {
      id: '/app/exercicios/$name'
      path: '/$name'
      fullPath: '/app/exercicios/$name'
      preLoaderRoute: typeof AppExerciciosNameRouteImport
      parentRoute: typeof AppExerciciosRoute
    }
    '/app/treinos/$id/foco': {
      id: '/app/treinos/$id/foco'
      path: '/foco'
      fullPath: '/app/treinos/$id/foco'
      preLoaderRoute: typeof AppTreinosIdFocoRouteImport
      parentRoute: typeof AppTreinosIdRoute
    }
  }
}

interface AppExerciciosRouteChildren {
  AppExerciciosNameRoute: typeof AppExerciciosNameRoute
}

const AppExerciciosRouteChildren: AppExerciciosRouteChildren = {
  AppExerciciosNameRoute: AppExerciciosNameRoute,
}

const AppExerciciosRouteWithChildren = AppExerciciosRoute._addFileChildren(
  AppExerciciosRouteChildren,
)

interface AppReceitasRouteChildren {
  AppReceitasIdRoute: typeof AppReceitasIdRoute
  AppReceitasIndexRoute: typeof AppReceitasIndexRoute
}

const AppReceitasRouteChildren: AppReceitasRouteChildren = {
  AppReceitasIdRoute: AppReceitasIdRoute,
  AppReceitasIndexRoute: AppReceitasIndexRoute,
}

const AppReceitasRouteWithChildren = AppReceitasRoute._addFileChildren(
  AppReceitasRouteChildren,
)

interface AppTemplatesRouteChildren {
  AppTemplatesIdRoute: typeof AppTemplatesIdRoute
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppTemplatesRouteChildren: AppTemplatesRouteChildren = {
  AppTemplatesIdRoute: AppTemplatesIdRoute,
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppTemplatesRouteWithChildren = AppTemplatesRoute._addFileChildren(
  AppTemplatesRouteChildren,
)

interface AppTreinosIdRouteChildren {
  AppTreinosIdFocoRoute: typeof AppTreinosIdFocoRoute
}

const AppTreinosIdRouteChildren: AppTreinosIdRouteChildren = {
  AppTreinosIdFocoRoute: AppTreinosIdFocoRoute,
}

const AppTreinosIdRouteWithChildren = AppTreinosIdRoute._addFileChildren(
  AppTreinosIdRouteChildren,
)

interface AppTreinosRouteChildren {
  AppTreinosIdRoute: typeof AppTreinosIdRouteWithChildren
  AppTreinosIndexRoute: typeof AppTreinosIndexRoute
}

const AppTreinosRouteChildren: AppTreinosRouteChildren = {
  AppTreinosIdRoute: AppTreinosIdRouteWithChildren,
  AppTreinosIndexRoute: AppTreinosIndexRoute,
}

const AppTreinosRouteWithChildren = AppTreinosRoute._addFileChildren(
  AppTreinosRouteChildren,
)

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCoachRoute: typeof AppCoachRoute
  AppExerciciosRoute: typeof AppExerciciosRouteWithChildren
  AppLembretesRoute: typeof AppLembretesRoute
  AppMetasRoute: typeof AppMetasRoute
  AppNutricaoRoute: typeof AppNutricaoRoute
  AppNutricaoHistoricoRoute: typeof AppNutricaoHistoricoRoute
  AppPesoRoute: typeof AppPesoRoute
  AppReceitasRoute: typeof AppReceitasRouteWithChildren
  AppRelatorioRoute: typeof AppRelatorioRoute
  AppTemplatesRoute: typeof AppTemplatesRouteWithChildren
  AppTreinosRoute: typeof AppTreinosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCoachRoute: AppCoachRoute,
  AppExerciciosRoute: AppExerciciosRouteWithChildren,
  AppLembretesRoute: AppLembretesRoute,
  AppMetasRoute: AppMetasRoute,
  AppNutricaoRoute: AppNutricaoRoute,
  AppNutricaoHistoricoRoute: AppNutricaoHistoricoRoute,
  AppPesoRoute: AppPesoRoute,
  AppReceitasRoute: AppReceitasRouteWithChildren,
  AppRelatorioRoute: AppRelatorioRoute,
  AppTemplatesRoute: AppTemplatesRouteWithChildren,
  AppTreinosRoute: AppTreinosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
