/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTreinosRouteImport } from './routes/app.treinos'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppPesoRouteImport } from './routes/app.peso'
import { Route as AppNutricaoRouteImport } from './routes/app.nutricao'
import { Route as AppMetasRouteImport } from './routes/app.metas'
import { Route as AppTreinosIndexRouteImport } from './routes/app.treinos.index'
import { Route as AppTemplatesIndexRouteImport } from './routes/app.templates.index'
import { Route as AppTreinosIdRouteImport } from './routes/app.treinos.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosRoute = AppTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppPesoRoute = AppPesoRouteImport.update({
  id: '/peso',
  path: '/peso',
  getParentRoute: () => AppRoute,
} as any)
const AppNutricaoRoute = AppNutricaoRouteImport.update({
  id: '/nutricao',
  path: '/nutricao',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppTreinosIndexRoute = AppTreinosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTreinosRoute,
} as any)
const AppTemplatesIndexRoute = AppTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTemplatesRoute,
} as any)
const AppTreinosIdRoute = AppTreinosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppTreinosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/metas': typeof AppMetasRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/peso': typeof AppPesoRoute
  '/app/templates': typeof AppTemplatesRouteWithChildren
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/treinos/': typeof AppTreinosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/metas': typeof AppMetasRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/peso': typeof AppPesoRoute
  '/app': typeof AppIndexRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/app/templates': typeof AppTemplatesIndexRoute
  '/app/treinos': typeof AppTreinosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/metas': typeof AppMetasRoute
  '/app/nutricao': typeof AppNutricaoRoute
  '/app/peso': typeof AppPesoRoute
  '/app/templates': typeof AppTemplatesRouteWithChildren
  '/app/treinos': typeof AppTreinosRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/treinos/$id': typeof AppTreinosIdRoute
  '/app/templates/': typeof AppTemplatesIndexRoute
  '/app/treinos/': typeof AppTreinosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/metas'
    | '/app/nutricao'
    | '/app/peso'
    | '/app/templates'
    | '/app/treinos'
    | '/app/'
    | '/app/treinos/$id'
    | '/app/templates/'
    | '/app/treinos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/metas'
    | '/app/nutricao'
    | '/app/peso'
    | '/app'
    | '/app/treinos/$id'
    | '/app/templates'
    | '/app/treinos'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/metas'
    | '/app/nutricao'
    | '/app/peso'
    | '/app/templates'
    | '/app/treinos'
    | '/app/'
    | '/app/treinos/$id'
    | '/app/templates/'
    | '/app/treinos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos': {
      id: '/app/treinos'
      path: '/treinos'
      fullPath: '/app/treinos'
      preLoaderRoute: typeof AppTreinosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/peso': {
      id: '/app/peso'
      path: '/peso'
      fullPath: '/app/peso'
      preLoaderRoute: typeof AppPesoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nutricao': {
      id: '/app/nutricao'
      path: '/nutricao'
      fullPath: '/app/nutricao'
      preLoaderRoute: typeof AppNutricaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/treinos/': {
      id: '/app/treinos/'
      path: '/'
      fullPath: '/app/treinos/'
      preLoaderRoute: typeof AppTreinosIndexRouteImport
      parentRoute: typeof AppTreinosRoute
    }
    '/app/templates/': {
      id: '/app/templates/'
      path: '/'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AppTemplatesIndexRouteImport
      parentRoute: typeof AppTemplatesRoute
    }
    '/app/treinos/$id': {
      id: '/app/treinos/$id'
      path: '/$id'
      fullPath: '/app/treinos/$id'
      preLoaderRoute: typeof AppTreinosIdRouteImport
      parentRoute: typeof AppTreinosRoute
    }
  }
}

interface AppTemplatesRouteChildren {
  AppTemplatesIndexRoute: typeof AppTemplatesIndexRoute
}

const AppTemplatesRouteChildren: AppTemplatesRouteChildren = {
  AppTemplatesIndexRoute: AppTemplatesIndexRoute,
}

const AppTemplatesRouteWithChildren = AppTemplatesRoute._addFileChildren(
  AppTemplatesRouteChildren,
)

interface AppTreinosRouteChildren {
  AppTreinosIdRoute: typeof AppTreinosIdRoute
  AppTreinosIndexRoute: typeof AppTreinosIndexRoute
}

const AppTreinosRouteChildren: AppTreinosRouteChildren = {
  AppTreinosIdRoute: AppTreinosIdRoute,
  AppTreinosIndexRoute: AppTreinosIndexRoute,
}

const AppTreinosRouteWithChildren = AppTreinosRoute._addFileChildren(
  AppTreinosRouteChildren,
)

interface AppRouteChildren {
  AppMetasRoute: typeof AppMetasRoute
  AppNutricaoRoute: typeof AppNutricaoRoute
  AppPesoRoute: typeof AppPesoRoute
  AppTemplatesRoute: typeof AppTemplatesRouteWithChildren
  AppTreinosRoute: typeof AppTreinosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMetasRoute: AppMetasRoute,
  AppNutricaoRoute: AppNutricaoRoute,
  AppPesoRoute: AppPesoRoute,
  AppTemplatesRoute: AppTemplatesRouteWithChildren,
  AppTreinosRoute: AppTreinosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
