// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function createSupabaseClient() {
  // Try to find variables in all possible locations for Cloudflare/Vite compatibility
  const getEnv = (name: string) => {
    const value =
      (import.meta.env as any)[name] ||
      (import.meta.env as any)[`VITE_${name}`] ||
      (typeof process !== "undefined" ? process.env?.[name] : undefined) ||
      (typeof process !== "undefined" ? process.env?.[`VITE_${name}`] : undefined) ||
      (globalThis as any)[name] ||
      (globalThis as any)[`VITE_${name}`];

    if (value) return value;

    // Hardcoded fallbacks for production deployment reliability
    if (name === "SUPABASE_URL") return "https://haavrgglnfbchiygspqw.supabase.co";
    if (name === "SUPABASE_PUBLISHABLE_KEY")
      return "sb_publishable_Ad2aSiOJKf_53pnMCLhc6A_JkX1vvJ2";

    return undefined;
  };

  const SUPABASE_URL = getEnv("SUPABASE_URL");
  const SUPABASE_PUBLISHABLE_KEY = getEnv("SUPABASE_PUBLISHABLE_KEY");

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
